-- Adopt existing MVP; bootstrap only on an empty Supabase public schema.
DO $baseline$
BEGIN
IF to_regclass('public.profiles') IS NULL THEN
EXECUTE $bootstrap$
-- Baseline captured from project jpoktrdyehalxkhdhkzu; no user data.
CREATE TYPE public."account_status" AS ENUM ('active','suspended','deleted');
CREATE TYPE public."auth_provider_type" AS ENUM ('email','google','apple','anonymous','other');
CREATE TYPE public."checkpoint_reward_type" AS ENUM ('landmark','food','province_item','energy');
CREATE TYPE public."energy_source_type" AS ENUM ('mission','checkin','journal','streak','checkpoint_reward','system_reward','adjustment');
CREATE TYPE public."future_letter_recipient_type" AS ENUM ('self','other');
CREATE TYPE public."future_letter_status" AS ENUM ('draft','scheduled','available','opened','cancelled');
CREATE TYPE public."journal_type" AS ENUM ('daily','yearly','future_letter');
CREATE TYPE public."journey_status" AS ENUM ('not_started','in_progress','completed','paused');
CREATE TYPE public."media_type" AS ENUM ('image','audio','video','document');
CREATE TYPE public."mission_difficulty" AS ENUM ('easy','medium','hard');
CREATE TYPE public."mission_source_type" AS ENUM ('system','mood_checkin','user_created','yearly_goal','event','admin');
CREATE TYPE public."mission_status" AS ENUM ('pending','in_progress','completed','skipped','expired','cancelled');
CREATE TYPE public."mission_type" AS ENUM ('daily','weekly','monthly','yearly','one_time','custom');
CREATE TYPE public."mood_type" AS ENUM ('great','good','okay','sad','awful');
CREATE TYPE public."progress_status" AS ENUM ('locked','in_progress','completed');
CREATE TYPE public."province_item_type" AS ENUM ('sticker','badge','souvenir','cloud_accessory','background','sound','frame');
CREATE TYPE public."rarity_type" AS ENUM ('common','uncommon','rare','epic','legendary');
CREATE TYPE public."region_type" AS ENUM ('north','central','south');
CREATE TYPE public."target_mood_type" AS ENUM ('great','good','okay','sad','awful','all');
CREATE TYPE public."theme_mode_type" AS ENUM ('system','light','dark');
CREATE TYPE public."travel_event_type" AS ENUM ('journey_started','energy_earned','checkpoint_started','checkpoint_completed','province_unlocked','province_completed','reward_unlocked');
CREATE TYPE public."upload_status" AS ENUM ('waiting','uploading','completed','failed');
CREATE TYPE public."yearly_journal_status" AS ENUM ('draft','in_progress','completed');
CREATE TABLE public."checkpoint_rewards" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "checkpoint_id" bigint NOT NULL,
  "reward_type" checkpoint_reward_type NOT NULL,
  "landmark_id" bigint,
  "food_id" bigint,
  "province_item_id" bigint,
  "energy_amount" integer,
  "quantity" integer DEFAULT 1 NOT NULL,
  "order_index" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."daily_checkins" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "checkin_at" timestamp with time zone DEFAULT now() NOT NULL,
  "checkin_date" date GENERATED ALWAYS AS (((checkin_at AT TIME ZONE 'Asia/Ho_Chi_Minh'::text))::date) STORED,
  "mood" mood_type NOT NULL,
  "mood_score" smallint NOT NULL,
  "energy_level" smallint,
  "note_short" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
CREATE TABLE public."daily_journals" (
  "journal_id" uuid NOT NULL,
  "checkin_id" uuid,
  "entry_date" date DEFAULT CURRENT_DATE NOT NULL,
  "content" text NOT NULL,
  "mood" mood_type,
  "mood_score" smallint,
  "weather_note" text,
  "location_note" text,
  "is_draft" boolean DEFAULT false NOT NULL
);
CREATE TABLE public."energy_transactions" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "source_type" energy_source_type NOT NULL,
  "source_id" uuid,
  "amount" integer NOT NULL,
  "balance_after" integer NOT NULL,
  "description" text,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."foods" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "province_id" bigint NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "story_content" text,
  "asset_path" text,
  "order_index" integer DEFAULT 0 NOT NULL,
  "rarity" rarity_type DEFAULT 'common'::rarity_type NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."future_letters" (
  "journal_id" uuid NOT NULL,
  "content_encrypted" text NOT NULL,
  "written_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deliver_at" timestamp with time zone NOT NULL,
  "opened_at" timestamp with time zone,
  "status" future_letter_status DEFAULT 'draft'::future_letter_status NOT NULL,
  "recipient_type" future_letter_recipient_type DEFAULT 'self'::future_letter_recipient_type NOT NULL,
  "recipient_name" text,
  "allow_edit_before_delivery" boolean DEFAULT true NOT NULL,
  "notification_scheduled" boolean DEFAULT false NOT NULL,
  "notification_sent_at" timestamp with time zone
);
CREATE TABLE public."journal_media" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "journal_id" uuid NOT NULL,
  "media_type" media_type NOT NULL,
  "storage_bucket" text,
  "storage_path" text,
  "remote_url" text,
  "thumbnail_path" text,
  "duration_seconds" integer,
  "file_size_bytes" bigint,
  "mime_type" text,
  "upload_status" upload_status DEFAULT 'waiting'::upload_status NOT NULL,
  "order_index" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
CREATE TABLE public."journal_tag_assignments" (
  "journal_id" uuid NOT NULL,
  "tag_id" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."journal_tags" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "name" text NOT NULL,
  "normalized_name" text GENERATED ALWAYS AS (lower(TRIM(BOTH FROM name))) STORED,
  "icon_name" text,
  "color_value" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
CREATE TABLE public."journals" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "journal_type" journal_type NOT NULL,
  "title" text,
  "preview_text" text,
  "cover_asset_path" text,
  "is_favorite" boolean DEFAULT false NOT NULL,
  "is_archived" boolean DEFAULT false NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
CREATE TABLE public."landmarks" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "province_id" bigint NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "story_content" text,
  "asset_path" text,
  "latitude" numeric(9,6),
  "longitude" numeric(9,6),
  "order_index" integer DEFAULT 0 NOT NULL,
  "rarity" rarity_type DEFAULT 'common'::rarity_type NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."mission_templates" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" text NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "mission_type" mission_type DEFAULT 'daily'::mission_type NOT NULL,
  "target_mood" target_mood_type DEFAULT 'all'::target_mood_type NOT NULL,
  "default_energy_reward" integer DEFAULT 0 NOT NULL,
  "difficulty" mission_difficulty DEFAULT 'easy'::mission_difficulty NOT NULL,
  "estimated_minutes" integer,
  "icon_asset_path" text,
  "is_system" boolean DEFAULT true NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."profiles" (
  "id" uuid NOT NULL,
  "display_name" text,
  "avatar_url" text,
  "auth_provider" auth_provider_type DEFAULT 'email'::auth_provider_type NOT NULL,
  "account_status" account_status DEFAULT 'active'::account_status NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "last_synced_at" timestamp with time zone,
  "deleted_at" timestamp with time zone
);
CREATE TABLE public."province_checkpoints" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "province_id" bigint NOT NULL,
  "checkpoint_number" integer NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "required_energy" integer DEFAULT 0 NOT NULL,
  "order_index" integer DEFAULT 0 NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."province_items" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "province_id" bigint NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "item_type" province_item_type NOT NULL,
  "description" text,
  "asset_path" text,
  "order_index" integer DEFAULT 0 NOT NULL,
  "rarity" rarity_type DEFAULT 'common'::rarity_type NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."provinces" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "region" region_type,
  "order_index" integer DEFAULT 0 NOT NULL,
  "cover_asset_path" text,
  "map_asset_path" text,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."travel_events" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "province_id" bigint,
  "checkpoint_id" bigint,
  "event_type" travel_event_type NOT NULL,
  "energy_amount" integer,
  "source_id" uuid,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."travel_progress" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "current_province_id" bigint,
  "current_checkpoint_id" bigint,
  "current_energy" integer DEFAULT 0 NOT NULL,
  "lifetime_energy" bigint DEFAULT 0 NOT NULL,
  "journey_status" journey_status DEFAULT 'not_started'::journey_status NOT NULL,
  "started_at" timestamp with time zone,
  "last_progress_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."unlocked_foods" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "food_id" bigint NOT NULL,
  "unlocked_at" timestamp with time zone DEFAULT now() NOT NULL,
  "unlock_source" text,
  "is_viewed" boolean DEFAULT false NOT NULL
);
CREATE TABLE public."unlocked_landmarks" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "landmark_id" bigint NOT NULL,
  "unlocked_at" timestamp with time zone DEFAULT now() NOT NULL,
  "unlock_source" text,
  "is_viewed" boolean DEFAULT false NOT NULL
);
CREATE TABLE public."unlocked_province_items" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "province_item_id" bigint NOT NULL,
  "unlocked_at" timestamp with time zone DEFAULT now() NOT NULL,
  "unlock_source" text,
  "is_viewed" boolean DEFAULT false NOT NULL,
  "is_equipped" boolean DEFAULT false NOT NULL,
  "equipped_at" timestamp with time zone
);
CREATE TABLE public."unlocked_provinces" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "province_id" bigint NOT NULL,
  "unlocked_at" timestamp with time zone DEFAULT now() NOT NULL,
  "completed_at" timestamp with time zone,
  "completion_percent" smallint DEFAULT 0 NOT NULL
);
CREATE TABLE public."user_checkpoint_progress" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "checkpoint_id" bigint NOT NULL,
  "earned_energy" integer DEFAULT 0 NOT NULL,
  "status" progress_status DEFAULT 'locked'::progress_status NOT NULL,
  "started_at" timestamp with time zone,
  "completed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."user_missions" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "template_id" bigint,
  "source_type" mission_source_type DEFAULT 'system'::mission_source_type NOT NULL,
  "source_checkin_id" uuid,
  "mission_type" mission_type NOT NULL,
  "title_snapshot" text NOT NULL,
  "description_snapshot" text,
  "energy_reward" integer DEFAULT 0 NOT NULL,
  "start_at" timestamp with time zone DEFAULT now() NOT NULL,
  "due_at" timestamp with time zone,
  "status" mission_status DEFAULT 'pending'::mission_status NOT NULL,
  "completed_at" timestamp with time zone,
  "reward_claimed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "deleted_at" timestamp with time zone
);
CREATE TABLE public."user_settings" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "cloud_name" text DEFAULT 'Mây'::text,
  "theme_mode" theme_mode_type DEFAULT 'system'::theme_mode_type NOT NULL,
  "language_code" text DEFAULT 'vi'::text NOT NULL,
  "sound_enabled" boolean DEFAULT true NOT NULL,
  "background_music_enabled" boolean DEFAULT true NOT NULL,
  "notification_enabled" boolean DEFAULT true NOT NULL,
  "daily_reminder_time" time without time zone,
  "biometric_lock_enabled" boolean DEFAULT false NOT NULL,
  "ai_personalization_enabled" boolean DEFAULT false NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."yearly_goals" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "yearly_journal_id" uuid NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "progress_percent" smallint DEFAULT 0 NOT NULL,
  "is_completed" boolean DEFAULT false NOT NULL,
  "completed_at" timestamp with time zone,
  "order_index" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."yearly_highlights" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "yearly_journal_id" uuid NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "event_date" date,
  "order_index" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."yearly_journals" (
  "journal_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "year" integer NOT NULL,
  "opening_message" text,
  "reflection_content" text,
  "gratitude_note" text,
  "overall_mood_score" numeric(3,2),
  "status" yearly_journal_status DEFAULT 'draft'::yearly_journal_status NOT NULL,
  "completed_at" timestamp with time zone
);
CREATE TABLE public."yearly_lessons" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "yearly_journal_id" uuid NOT NULL,
  "content" text NOT NULL,
  "order_index" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE public."checkpoint_rewards" ADD CONSTRAINT "checkpoint_rewards_check" CHECK ((((reward_type = 'landmark'::checkpoint_reward_type) AND (landmark_id IS NOT NULL) AND (food_id IS NULL) AND (province_item_id IS NULL) AND (energy_amount IS NULL)) OR ((reward_type = 'food'::checkpoint_reward_type) AND (landmark_id IS NULL) AND (food_id IS NOT NULL) AND (province_item_id IS NULL) AND (energy_amount IS NULL)) OR ((reward_type = 'province_item'::checkpoint_reward_type) AND (landmark_id IS NULL) AND (food_id IS NULL) AND (province_item_id IS NOT NULL) AND (energy_amount IS NULL)) OR ((reward_type = 'energy'::checkpoint_reward_type) AND (landmark_id IS NULL) AND (food_id IS NULL) AND (province_item_id IS NULL) AND (energy_amount IS NOT NULL))));
ALTER TABLE public."checkpoint_rewards" ADD CONSTRAINT "checkpoint_rewards_energy_amount_check" CHECK (((energy_amount IS NULL) OR (energy_amount > 0)));
ALTER TABLE public."checkpoint_rewards" ADD CONSTRAINT "checkpoint_rewards_pkey" PRIMARY KEY (id);
ALTER TABLE public."checkpoint_rewards" ADD CONSTRAINT "checkpoint_rewards_quantity_check" CHECK ((quantity > 0));
ALTER TABLE public."daily_checkins" ADD CONSTRAINT "daily_checkins_energy_level_check" CHECK (((energy_level >= 1) AND (energy_level <= 5)));
ALTER TABLE public."daily_checkins" ADD CONSTRAINT "daily_checkins_mood_score_check" CHECK (((mood_score >= 1) AND (mood_score <= 5)));
ALTER TABLE public."daily_checkins" ADD CONSTRAINT "daily_checkins_pkey" PRIMARY KEY (id);
ALTER TABLE public."daily_journals" ADD CONSTRAINT "daily_journals_mood_score_check" CHECK (((mood_score >= 1) AND (mood_score <= 5)));
ALTER TABLE public."daily_journals" ADD CONSTRAINT "daily_journals_pkey" PRIMARY KEY (journal_id);
ALTER TABLE public."energy_transactions" ADD CONSTRAINT "energy_transactions_amount_check" CHECK ((amount <> 0));
ALTER TABLE public."energy_transactions" ADD CONSTRAINT "energy_transactions_balance_after_check" CHECK ((balance_after >= 0));
ALTER TABLE public."energy_transactions" ADD CONSTRAINT "energy_transactions_pkey" PRIMARY KEY (id);
ALTER TABLE public."foods" ADD CONSTRAINT "foods_code_key" UNIQUE (code);
ALTER TABLE public."foods" ADD CONSTRAINT "foods_pkey" PRIMARY KEY (id);
ALTER TABLE public."foods" ADD CONSTRAINT "foods_province_id_name_key" UNIQUE (province_id, name);
ALTER TABLE public."future_letters" ADD CONSTRAINT "future_letters_check" CHECK ((deliver_at > written_at));
ALTER TABLE public."future_letters" ADD CONSTRAINT "future_letters_check1" CHECK (((recipient_type = 'self'::future_letter_recipient_type) OR (recipient_name IS NOT NULL)));
ALTER TABLE public."future_letters" ADD CONSTRAINT "future_letters_pkey" PRIMARY KEY (journal_id);
ALTER TABLE public."journal_media" ADD CONSTRAINT "journal_media_duration_seconds_check" CHECK (((duration_seconds IS NULL) OR (duration_seconds >= 0)));
ALTER TABLE public."journal_media" ADD CONSTRAINT "journal_media_file_size_bytes_check" CHECK (((file_size_bytes IS NULL) OR (file_size_bytes >= 0)));
ALTER TABLE public."journal_media" ADD CONSTRAINT "journal_media_pkey" PRIMARY KEY (id);
ALTER TABLE public."journal_tag_assignments" ADD CONSTRAINT "journal_tag_assignments_pkey" PRIMARY KEY (journal_id, tag_id);
ALTER TABLE public."journal_tags" ADD CONSTRAINT "journal_tags_pkey" PRIMARY KEY (id);
ALTER TABLE public."journal_tags" ADD CONSTRAINT "journal_tags_user_id_normalized_name_key" UNIQUE (user_id, normalized_name);
ALTER TABLE public."journals" ADD CONSTRAINT "journals_pkey" PRIMARY KEY (id);
ALTER TABLE public."landmarks" ADD CONSTRAINT "landmarks_code_key" UNIQUE (code);
ALTER TABLE public."landmarks" ADD CONSTRAINT "landmarks_latitude_check" CHECK (((latitude IS NULL) OR ((latitude >= ('-90'::integer)::numeric) AND (latitude <= (90)::numeric))));
ALTER TABLE public."landmarks" ADD CONSTRAINT "landmarks_longitude_check" CHECK (((longitude IS NULL) OR ((longitude >= ('-180'::integer)::numeric) AND (longitude <= (180)::numeric))));
ALTER TABLE public."landmarks" ADD CONSTRAINT "landmarks_pkey" PRIMARY KEY (id);
ALTER TABLE public."landmarks" ADD CONSTRAINT "landmarks_province_id_name_key" UNIQUE (province_id, name);
ALTER TABLE public."mission_templates" ADD CONSTRAINT "mission_templates_code_key" UNIQUE (code);
ALTER TABLE public."mission_templates" ADD CONSTRAINT "mission_templates_default_energy_reward_check" CHECK ((default_energy_reward >= 0));
ALTER TABLE public."mission_templates" ADD CONSTRAINT "mission_templates_estimated_minutes_check" CHECK (((estimated_minutes IS NULL) OR (estimated_minutes >= 0)));
ALTER TABLE public."mission_templates" ADD CONSTRAINT "mission_templates_pkey" PRIMARY KEY (id);
ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY (id);
ALTER TABLE public."province_checkpoints" ADD CONSTRAINT "province_checkpoints_checkpoint_number_check" CHECK ((checkpoint_number > 0));
ALTER TABLE public."province_checkpoints" ADD CONSTRAINT "province_checkpoints_pkey" PRIMARY KEY (id);
ALTER TABLE public."province_checkpoints" ADD CONSTRAINT "province_checkpoints_province_id_checkpoint_number_key" UNIQUE (province_id, checkpoint_number);
ALTER TABLE public."province_checkpoints" ADD CONSTRAINT "province_checkpoints_required_energy_check" CHECK ((required_energy >= 0));
ALTER TABLE public."province_items" ADD CONSTRAINT "province_items_code_key" UNIQUE (code);
ALTER TABLE public."province_items" ADD CONSTRAINT "province_items_pkey" PRIMARY KEY (id);
ALTER TABLE public."province_items" ADD CONSTRAINT "province_items_province_id_code_key" UNIQUE (province_id, code);
ALTER TABLE public."provinces" ADD CONSTRAINT "provinces_code_key" UNIQUE (code);
ALTER TABLE public."provinces" ADD CONSTRAINT "provinces_name_key" UNIQUE (name);
ALTER TABLE public."provinces" ADD CONSTRAINT "provinces_pkey" PRIMARY KEY (id);
ALTER TABLE public."travel_events" ADD CONSTRAINT "travel_events_pkey" PRIMARY KEY (id);
ALTER TABLE public."travel_progress" ADD CONSTRAINT "travel_progress_current_energy_check" CHECK ((current_energy >= 0));
ALTER TABLE public."travel_progress" ADD CONSTRAINT "travel_progress_lifetime_energy_check" CHECK ((lifetime_energy >= 0));
ALTER TABLE public."travel_progress" ADD CONSTRAINT "travel_progress_pkey" PRIMARY KEY (id);
ALTER TABLE public."travel_progress" ADD CONSTRAINT "travel_progress_user_id_key" UNIQUE (user_id);
ALTER TABLE public."unlocked_foods" ADD CONSTRAINT "unlocked_foods_pkey" PRIMARY KEY (id);
ALTER TABLE public."unlocked_foods" ADD CONSTRAINT "unlocked_foods_user_id_food_id_key" UNIQUE (user_id, food_id);
ALTER TABLE public."unlocked_landmarks" ADD CONSTRAINT "unlocked_landmarks_pkey" PRIMARY KEY (id);
ALTER TABLE public."unlocked_landmarks" ADD CONSTRAINT "unlocked_landmarks_user_id_landmark_id_key" UNIQUE (user_id, landmark_id);
ALTER TABLE public."unlocked_province_items" ADD CONSTRAINT "unlocked_province_items_check" CHECK (((is_equipped = false) OR (equipped_at IS NOT NULL)));
ALTER TABLE public."unlocked_province_items" ADD CONSTRAINT "unlocked_province_items_pkey" PRIMARY KEY (id);
ALTER TABLE public."unlocked_province_items" ADD CONSTRAINT "unlocked_province_items_user_id_province_item_id_key" UNIQUE (user_id, province_item_id);
ALTER TABLE public."unlocked_provinces" ADD CONSTRAINT "unlocked_provinces_completion_percent_check" CHECK (((completion_percent >= 0) AND (completion_percent <= 100)));
ALTER TABLE public."unlocked_provinces" ADD CONSTRAINT "unlocked_provinces_pkey" PRIMARY KEY (id);
ALTER TABLE public."unlocked_provinces" ADD CONSTRAINT "unlocked_provinces_user_id_province_id_key" UNIQUE (user_id, province_id);
ALTER TABLE public."user_checkpoint_progress" ADD CONSTRAINT "user_checkpoint_progress_check" CHECK (((status <> 'completed'::progress_status) OR (completed_at IS NOT NULL)));
ALTER TABLE public."user_checkpoint_progress" ADD CONSTRAINT "user_checkpoint_progress_earned_energy_check" CHECK ((earned_energy >= 0));
ALTER TABLE public."user_checkpoint_progress" ADD CONSTRAINT "user_checkpoint_progress_pkey" PRIMARY KEY (id);
ALTER TABLE public."user_checkpoint_progress" ADD CONSTRAINT "user_checkpoint_progress_user_id_checkpoint_id_key" UNIQUE (user_id, checkpoint_id);
ALTER TABLE public."user_missions" ADD CONSTRAINT "user_missions_check" CHECK (((due_at IS NULL) OR (due_at >= start_at)));
ALTER TABLE public."user_missions" ADD CONSTRAINT "user_missions_check1" CHECK (((status <> 'completed'::mission_status) OR (completed_at IS NOT NULL)));
ALTER TABLE public."user_missions" ADD CONSTRAINT "user_missions_energy_reward_check" CHECK ((energy_reward >= 0));
ALTER TABLE public."user_missions" ADD CONSTRAINT "user_missions_pkey" PRIMARY KEY (id);
ALTER TABLE public."user_settings" ADD CONSTRAINT "user_settings_pkey" PRIMARY KEY (id);
ALTER TABLE public."user_settings" ADD CONSTRAINT "user_settings_user_id_key" UNIQUE (user_id);
ALTER TABLE public."yearly_goals" ADD CONSTRAINT "yearly_goals_pkey" PRIMARY KEY (id);
ALTER TABLE public."yearly_goals" ADD CONSTRAINT "yearly_goals_progress_percent_check" CHECK (((progress_percent >= 0) AND (progress_percent <= 100)));
ALTER TABLE public."yearly_highlights" ADD CONSTRAINT "yearly_highlights_pkey" PRIMARY KEY (id);
ALTER TABLE public."yearly_journals" ADD CONSTRAINT "yearly_journals_overall_mood_score_check" CHECK (((overall_mood_score IS NULL) OR ((overall_mood_score >= (1)::numeric) AND (overall_mood_score <= (5)::numeric))));
ALTER TABLE public."yearly_journals" ADD CONSTRAINT "yearly_journals_pkey" PRIMARY KEY (journal_id);
ALTER TABLE public."yearly_journals" ADD CONSTRAINT "yearly_journals_user_id_year_key" UNIQUE (user_id, year);
ALTER TABLE public."yearly_journals" ADD CONSTRAINT "yearly_journals_year_check" CHECK (((year >= 1900) AND (year <= 2200)));
ALTER TABLE public."yearly_lessons" ADD CONSTRAINT "yearly_lessons_pkey" PRIMARY KEY (id);
ALTER TABLE public."checkpoint_rewards" ADD CONSTRAINT "checkpoint_rewards_checkpoint_id_fkey" FOREIGN KEY (checkpoint_id) REFERENCES province_checkpoints(id) ON DELETE CASCADE;
ALTER TABLE public."checkpoint_rewards" ADD CONSTRAINT "checkpoint_rewards_food_id_fkey" FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE CASCADE;
ALTER TABLE public."checkpoint_rewards" ADD CONSTRAINT "checkpoint_rewards_landmark_id_fkey" FOREIGN KEY (landmark_id) REFERENCES landmarks(id) ON DELETE CASCADE;
ALTER TABLE public."checkpoint_rewards" ADD CONSTRAINT "checkpoint_rewards_province_item_id_fkey" FOREIGN KEY (province_item_id) REFERENCES province_items(id) ON DELETE CASCADE;
ALTER TABLE public."daily_checkins" ADD CONSTRAINT "daily_checkins_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."daily_journals" ADD CONSTRAINT "daily_journals_checkin_id_fkey" FOREIGN KEY (checkin_id) REFERENCES daily_checkins(id) ON DELETE SET NULL;
ALTER TABLE public."daily_journals" ADD CONSTRAINT "daily_journals_journal_id_fkey" FOREIGN KEY (journal_id) REFERENCES journals(id) ON DELETE CASCADE;
ALTER TABLE public."energy_transactions" ADD CONSTRAINT "energy_transactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."foods" ADD CONSTRAINT "foods_province_id_fkey" FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE CASCADE;
ALTER TABLE public."future_letters" ADD CONSTRAINT "future_letters_journal_id_fkey" FOREIGN KEY (journal_id) REFERENCES journals(id) ON DELETE CASCADE;
ALTER TABLE public."journal_media" ADD CONSTRAINT "journal_media_journal_id_fkey" FOREIGN KEY (journal_id) REFERENCES journals(id) ON DELETE CASCADE;
ALTER TABLE public."journal_tag_assignments" ADD CONSTRAINT "journal_tag_assignments_journal_id_fkey" FOREIGN KEY (journal_id) REFERENCES journals(id) ON DELETE CASCADE;
ALTER TABLE public."journal_tag_assignments" ADD CONSTRAINT "journal_tag_assignments_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES journal_tags(id) ON DELETE CASCADE;
ALTER TABLE public."journal_tags" ADD CONSTRAINT "journal_tags_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."journals" ADD CONSTRAINT "journals_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."landmarks" ADD CONSTRAINT "landmarks_province_id_fkey" FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE CASCADE;
ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."province_checkpoints" ADD CONSTRAINT "province_checkpoints_province_id_fkey" FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE CASCADE;
ALTER TABLE public."province_items" ADD CONSTRAINT "province_items_province_id_fkey" FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE CASCADE;
ALTER TABLE public."travel_events" ADD CONSTRAINT "travel_events_checkpoint_id_fkey" FOREIGN KEY (checkpoint_id) REFERENCES province_checkpoints(id) ON DELETE SET NULL;
ALTER TABLE public."travel_events" ADD CONSTRAINT "travel_events_province_id_fkey" FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE SET NULL;
ALTER TABLE public."travel_events" ADD CONSTRAINT "travel_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."travel_progress" ADD CONSTRAINT "travel_progress_current_checkpoint_id_fkey" FOREIGN KEY (current_checkpoint_id) REFERENCES province_checkpoints(id) ON DELETE SET NULL;
ALTER TABLE public."travel_progress" ADD CONSTRAINT "travel_progress_current_province_id_fkey" FOREIGN KEY (current_province_id) REFERENCES provinces(id) ON DELETE SET NULL;
ALTER TABLE public."travel_progress" ADD CONSTRAINT "travel_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."unlocked_foods" ADD CONSTRAINT "unlocked_foods_food_id_fkey" FOREIGN KEY (food_id) REFERENCES foods(id) ON DELETE CASCADE;
ALTER TABLE public."unlocked_foods" ADD CONSTRAINT "unlocked_foods_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."unlocked_landmarks" ADD CONSTRAINT "unlocked_landmarks_landmark_id_fkey" FOREIGN KEY (landmark_id) REFERENCES landmarks(id) ON DELETE CASCADE;
ALTER TABLE public."unlocked_landmarks" ADD CONSTRAINT "unlocked_landmarks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."unlocked_province_items" ADD CONSTRAINT "unlocked_province_items_province_item_id_fkey" FOREIGN KEY (province_item_id) REFERENCES province_items(id) ON DELETE CASCADE;
ALTER TABLE public."unlocked_province_items" ADD CONSTRAINT "unlocked_province_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."unlocked_provinces" ADD CONSTRAINT "unlocked_provinces_province_id_fkey" FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE CASCADE;
ALTER TABLE public."unlocked_provinces" ADD CONSTRAINT "unlocked_provinces_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."user_checkpoint_progress" ADD CONSTRAINT "user_checkpoint_progress_checkpoint_id_fkey" FOREIGN KEY (checkpoint_id) REFERENCES province_checkpoints(id) ON DELETE CASCADE;
ALTER TABLE public."user_checkpoint_progress" ADD CONSTRAINT "user_checkpoint_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."user_missions" ADD CONSTRAINT "user_missions_source_checkin_id_fkey" FOREIGN KEY (source_checkin_id) REFERENCES daily_checkins(id) ON DELETE SET NULL;
ALTER TABLE public."user_missions" ADD CONSTRAINT "user_missions_template_id_fkey" FOREIGN KEY (template_id) REFERENCES mission_templates(id) ON DELETE SET NULL;
ALTER TABLE public."user_missions" ADD CONSTRAINT "user_missions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."user_settings" ADD CONSTRAINT "user_settings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."yearly_goals" ADD CONSTRAINT "yearly_goals_yearly_journal_id_fkey" FOREIGN KEY (yearly_journal_id) REFERENCES yearly_journals(journal_id) ON DELETE CASCADE;
ALTER TABLE public."yearly_highlights" ADD CONSTRAINT "yearly_highlights_yearly_journal_id_fkey" FOREIGN KEY (yearly_journal_id) REFERENCES yearly_journals(journal_id) ON DELETE CASCADE;
ALTER TABLE public."yearly_journals" ADD CONSTRAINT "yearly_journals_journal_id_fkey" FOREIGN KEY (journal_id) REFERENCES journals(id) ON DELETE CASCADE;
ALTER TABLE public."yearly_journals" ADD CONSTRAINT "yearly_journals_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public."yearly_lessons" ADD CONSTRAINT "yearly_lessons_yearly_journal_id_fkey" FOREIGN KEY (yearly_journal_id) REFERENCES yearly_journals(journal_id) ON DELETE CASCADE;
CREATE INDEX daily_checkins_user_date_idx ON public.daily_checkins USING btree (user_id, checkin_date DESC);
CREATE INDEX journals_user_updated_idx ON public.journals USING btree (user_id, updated_at DESC);
CREATE INDEX journals_user_type_idx ON public.journals USING btree (user_id, journal_type);
CREATE INDEX daily_journals_entry_date_idx ON public.daily_journals USING btree (entry_date DESC);
CREATE INDEX daily_journals_checkin_idx ON public.daily_journals USING btree (checkin_id);
CREATE INDEX yearly_journals_year_idx ON public.yearly_journals USING btree (user_id, year DESC);
CREATE INDEX yearly_goals_journal_idx ON public.yearly_goals USING btree (yearly_journal_id, order_index);
CREATE INDEX yearly_highlights_journal_idx ON public.yearly_highlights USING btree (yearly_journal_id, order_index);
CREATE INDEX yearly_lessons_journal_idx ON public.yearly_lessons USING btree (yearly_journal_id, order_index);
CREATE INDEX future_letters_deliver_at_idx ON public.future_letters USING btree (deliver_at) WHERE (status = 'scheduled'::future_letter_status);
CREATE INDEX journal_media_journal_idx ON public.journal_media USING btree (journal_id, order_index);
CREATE INDEX journal_tags_user_idx ON public.journal_tags USING btree (user_id);
CREATE INDEX journal_tag_assignments_tag_idx ON public.journal_tag_assignments USING btree (tag_id);
CREATE INDEX user_missions_user_status_idx ON public.user_missions USING btree (user_id, status, start_at DESC);
CREATE INDEX user_missions_due_idx ON public.user_missions USING btree (user_id, due_at) WHERE (status = ANY (ARRAY['pending'::mission_status, 'in_progress'::mission_status]));
CREATE INDEX user_checkpoint_progress_user_idx ON public.user_checkpoint_progress USING btree (user_id, status);
CREATE INDEX travel_events_user_time_idx ON public.travel_events USING btree (user_id, occurred_at DESC);
CREATE INDEX unlocked_provinces_user_idx ON public.unlocked_provinces USING btree (user_id, unlocked_at DESC);
CREATE INDEX unlocked_landmarks_user_idx ON public.unlocked_landmarks USING btree (user_id, unlocked_at DESC);
CREATE INDEX unlocked_foods_user_idx ON public.unlocked_foods USING btree (user_id, unlocked_at DESC);
CREATE INDEX unlocked_province_items_user_idx ON public.unlocked_province_items USING btree (user_id, unlocked_at DESC);
CREATE INDEX energy_transactions_user_time_idx ON public.energy_transactions USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX energy_transactions_unique_source_idx ON public.energy_transactions USING btree (user_id, source_type, source_id) WHERE (source_id IS NOT NULL);
CREATE INDEX mission_templates_active_mood_idx ON public.mission_templates USING btree (is_active, target_mood);
CREATE INDEX provinces_order_idx ON public.provinces USING btree (order_index);
CREATE INDEX landmarks_province_idx ON public.landmarks USING btree (province_id, order_index);
CREATE INDEX foods_province_idx ON public.foods USING btree (province_id, order_index);
CREATE INDEX province_items_province_idx ON public.province_items USING btree (province_id, item_type, order_index);
CREATE INDEX province_checkpoints_province_idx ON public.province_checkpoints USING btree (province_id, order_index);
CREATE INDEX checkpoint_rewards_checkpoint_idx ON public.checkpoint_rewards USING btree (checkpoint_id, order_index);
CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (
    id,
    display_name,
    avatar_url,
    auth_provider
  )
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'display_name',
      new.raw_user_meta_data ->> 'full_name'
    ),
    new.raw_user_meta_data ->> 'avatar_url',
    case
      when new.is_anonymous then 'anonymous'::public.auth_provider_type
      else 'email'::public.auth_provider_type
    end
  )
  on conflict (id) do nothing;

  insert into public.user_settings (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.validate_daily_journal_type()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if not exists (
    select 1
    from public.journals j
    where j.id = new.journal_id
      and j.journal_type = 'daily'
  ) then
    raise exception 'Journal must have journal_type = daily';
  end if;

  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.validate_yearly_journal_type()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if not exists (
    select 1
    from public.journals j
    where j.id = new.journal_id
      and j.journal_type = 'yearly'
      and j.user_id = new.user_id
  ) then
    raise exception 'Journal must have journal_type = yearly and matching user';
  end if;

  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.validate_future_letter_type()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if not exists (
    select 1
    from public.journals j
    where j.id = new.journal_id
      and j.journal_type = 'future_letter'
  ) then
    raise exception 'Journal must have journal_type = future_letter';
  end if;

  return new;
end;
$function$
;
CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER user_settings_set_updated_at BEFORE UPDATE ON public.user_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_auth_user();
CREATE TRIGGER daily_checkins_set_updated_at BEFORE UPDATE ON public.daily_checkins FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER journals_set_updated_at BEFORE UPDATE ON public.journals FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER yearly_goals_set_updated_at BEFORE UPDATE ON public.yearly_goals FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER yearly_highlights_set_updated_at BEFORE UPDATE ON public.yearly_highlights FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER yearly_lessons_set_updated_at BEFORE UPDATE ON public.yearly_lessons FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER journal_media_set_updated_at BEFORE UPDATE ON public.journal_media FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER journal_tags_set_updated_at BEFORE UPDATE ON public.journal_tags FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER mission_templates_set_updated_at BEFORE UPDATE ON public.mission_templates FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER user_missions_set_updated_at BEFORE UPDATE ON public.user_missions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER provinces_set_updated_at BEFORE UPDATE ON public.provinces FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER landmarks_set_updated_at BEFORE UPDATE ON public.landmarks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER foods_set_updated_at BEFORE UPDATE ON public.foods FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER province_items_set_updated_at BEFORE UPDATE ON public.province_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER province_checkpoints_set_updated_at BEFORE UPDATE ON public.province_checkpoints FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER travel_progress_set_updated_at BEFORE UPDATE ON public.travel_progress FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER user_checkpoint_progress_set_updated_at BEFORE UPDATE ON public.user_checkpoint_progress FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER validate_daily_journal BEFORE INSERT OR UPDATE ON public.daily_journals FOR EACH ROW EXECUTE FUNCTION validate_daily_journal_type();
CREATE TRIGGER validate_yearly_journal BEFORE INSERT OR UPDATE ON public.yearly_journals FOR EACH ROW EXECUTE FUNCTION validate_yearly_journal_type();
CREATE TRIGGER validate_future_letter BEFORE INSERT OR UPDATE ON public.future_letters FOR EACH ROW EXECUTE FUNCTION validate_future_letter_type();
ALTER TABLE public."checkpoint_rewards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."daily_checkins" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."daily_journals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."energy_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."foods" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."future_letters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."journal_media" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."journal_tag_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."journal_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."journals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."landmarks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."mission_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."province_checkpoints" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."province_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."provinces" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."travel_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."travel_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."unlocked_foods" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."unlocked_landmarks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."unlocked_province_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."unlocked_provinces" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_checkpoint_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_missions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."yearly_goals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."yearly_highlights" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."yearly_journals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."yearly_lessons" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_select_own" ON "public"."profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((( SELECT auth.uid() AS uid) = id));
CREATE POLICY "profiles_update_own" ON "public"."profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((( SELECT auth.uid() AS uid) = id)) WITH CHECK ((( SELECT auth.uid() AS uid) = id));
CREATE POLICY "settings_all_own" ON "public"."user_settings" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "checkins_all_own" ON "public"."daily_checkins" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "journals_all_own" ON "public"."journals" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "yearly_journals_all_own" ON "public"."yearly_journals" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "journal_tags_all_own" ON "public"."journal_tags" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "user_missions_all_own" ON "public"."user_missions" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "travel_progress_all_own" ON "public"."travel_progress" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "checkpoint_progress_all_own" ON "public"."user_checkpoint_progress" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "travel_events_all_own" ON "public"."travel_events" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "unlocked_provinces_all_own" ON "public"."unlocked_provinces" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "unlocked_landmarks_all_own" ON "public"."unlocked_landmarks" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "unlocked_foods_all_own" ON "public"."unlocked_foods" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "unlocked_items_all_own" ON "public"."unlocked_province_items" AS PERMISSIVE FOR ALL TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "energy_transactions_select_own" ON "public"."energy_transactions" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "daily_journals_all_own" ON "public"."daily_journals" AS PERMISSIVE FOR ALL TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM journals j
  WHERE ((j.id = daily_journals.journal_id) AND (j.user_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM journals j
  WHERE ((j.id = daily_journals.journal_id) AND (j.user_id = ( SELECT auth.uid() AS uid))))));
CREATE POLICY "future_letters_all_own" ON "public"."future_letters" AS PERMISSIVE FOR ALL TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM journals j
  WHERE ((j.id = future_letters.journal_id) AND (j.user_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM journals j
  WHERE ((j.id = future_letters.journal_id) AND (j.user_id = ( SELECT auth.uid() AS uid))))));
CREATE POLICY "journal_media_all_own" ON "public"."journal_media" AS PERMISSIVE FOR ALL TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM journals j
  WHERE ((j.id = journal_media.journal_id) AND (j.user_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM journals j
  WHERE ((j.id = journal_media.journal_id) AND (j.user_id = ( SELECT auth.uid() AS uid))))));
CREATE POLICY "yearly_goals_all_own" ON "public"."yearly_goals" AS PERMISSIVE FOR ALL TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM yearly_journals yj
  WHERE ((yj.journal_id = yearly_goals.yearly_journal_id) AND (yj.user_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM yearly_journals yj
  WHERE ((yj.journal_id = yearly_goals.yearly_journal_id) AND (yj.user_id = ( SELECT auth.uid() AS uid))))));
CREATE POLICY "yearly_highlights_all_own" ON "public"."yearly_highlights" AS PERMISSIVE FOR ALL TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM yearly_journals yj
  WHERE ((yj.journal_id = yearly_highlights.yearly_journal_id) AND (yj.user_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM yearly_journals yj
  WHERE ((yj.journal_id = yearly_highlights.yearly_journal_id) AND (yj.user_id = ( SELECT auth.uid() AS uid))))));
CREATE POLICY "yearly_lessons_all_own" ON "public"."yearly_lessons" AS PERMISSIVE FOR ALL TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM yearly_journals yj
  WHERE ((yj.journal_id = yearly_lessons.yearly_journal_id) AND (yj.user_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM yearly_journals yj
  WHERE ((yj.journal_id = yearly_lessons.yearly_journal_id) AND (yj.user_id = ( SELECT auth.uid() AS uid))))));
CREATE POLICY "journal_tag_assignments_all_own" ON "public"."journal_tag_assignments" AS PERMISSIVE FOR ALL TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM (journals j
     JOIN journal_tags t ON ((t.id = journal_tag_assignments.tag_id)))
  WHERE ((j.id = journal_tag_assignments.journal_id) AND (j.user_id = ( SELECT auth.uid() AS uid)) AND (t.user_id = ( SELECT auth.uid() AS uid)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM (journals j
     JOIN journal_tags t ON ((t.id = journal_tag_assignments.tag_id)))
  WHERE ((j.id = journal_tag_assignments.journal_id) AND (j.user_id = ( SELECT auth.uid() AS uid)) AND (t.user_id = ( SELECT auth.uid() AS uid))))));
CREATE POLICY "mission_templates_read" ON "public"."mission_templates" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
CREATE POLICY "provinces_read" ON "public"."provinces" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
CREATE POLICY "landmarks_read" ON "public"."landmarks" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
CREATE POLICY "foods_read" ON "public"."foods" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
CREATE POLICY "province_items_read" ON "public"."province_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
CREATE POLICY "province_checkpoints_read" ON "public"."province_checkpoints" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
CREATE POLICY "checkpoint_rewards_read" ON "public"."checkpoint_rewards" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
GRANT INSERT ON public."profiles" TO "anon";
GRANT SELECT ON public."profiles" TO "anon";
GRANT UPDATE ON public."profiles" TO "anon";
GRANT DELETE ON public."profiles" TO "anon";
GRANT TRUNCATE ON public."profiles" TO "anon";
GRANT REFERENCES ON public."profiles" TO "anon";
GRANT TRIGGER ON public."profiles" TO "anon";
GRANT INSERT ON public."profiles" TO "authenticated";
GRANT SELECT ON public."profiles" TO "authenticated";
GRANT UPDATE ON public."profiles" TO "authenticated";
GRANT DELETE ON public."profiles" TO "authenticated";
GRANT TRUNCATE ON public."profiles" TO "authenticated";
GRANT REFERENCES ON public."profiles" TO "authenticated";
GRANT TRIGGER ON public."profiles" TO "authenticated";
GRANT INSERT ON public."profiles" TO "service_role";
GRANT SELECT ON public."profiles" TO "service_role";
GRANT UPDATE ON public."profiles" TO "service_role";
GRANT DELETE ON public."profiles" TO "service_role";
GRANT TRUNCATE ON public."profiles" TO "service_role";
GRANT REFERENCES ON public."profiles" TO "service_role";
GRANT TRIGGER ON public."profiles" TO "service_role";
GRANT INSERT ON public."user_settings" TO "anon";
GRANT SELECT ON public."user_settings" TO "anon";
GRANT UPDATE ON public."user_settings" TO "anon";
GRANT DELETE ON public."user_settings" TO "anon";
GRANT TRUNCATE ON public."user_settings" TO "anon";
GRANT REFERENCES ON public."user_settings" TO "anon";
GRANT TRIGGER ON public."user_settings" TO "anon";
GRANT INSERT ON public."user_settings" TO "authenticated";
GRANT SELECT ON public."user_settings" TO "authenticated";
GRANT UPDATE ON public."user_settings" TO "authenticated";
GRANT DELETE ON public."user_settings" TO "authenticated";
GRANT TRUNCATE ON public."user_settings" TO "authenticated";
GRANT REFERENCES ON public."user_settings" TO "authenticated";
GRANT TRIGGER ON public."user_settings" TO "authenticated";
GRANT INSERT ON public."user_settings" TO "service_role";
GRANT SELECT ON public."user_settings" TO "service_role";
GRANT UPDATE ON public."user_settings" TO "service_role";
GRANT DELETE ON public."user_settings" TO "service_role";
GRANT TRUNCATE ON public."user_settings" TO "service_role";
GRANT REFERENCES ON public."user_settings" TO "service_role";
GRANT TRIGGER ON public."user_settings" TO "service_role";
GRANT INSERT ON public."daily_checkins" TO "anon";
GRANT SELECT ON public."daily_checkins" TO "anon";
GRANT UPDATE ON public."daily_checkins" TO "anon";
GRANT DELETE ON public."daily_checkins" TO "anon";
GRANT TRUNCATE ON public."daily_checkins" TO "anon";
GRANT REFERENCES ON public."daily_checkins" TO "anon";
GRANT TRIGGER ON public."daily_checkins" TO "anon";
GRANT INSERT ON public."daily_checkins" TO "authenticated";
GRANT SELECT ON public."daily_checkins" TO "authenticated";
GRANT UPDATE ON public."daily_checkins" TO "authenticated";
GRANT DELETE ON public."daily_checkins" TO "authenticated";
GRANT TRUNCATE ON public."daily_checkins" TO "authenticated";
GRANT REFERENCES ON public."daily_checkins" TO "authenticated";
GRANT TRIGGER ON public."daily_checkins" TO "authenticated";
GRANT INSERT ON public."daily_checkins" TO "service_role";
GRANT SELECT ON public."daily_checkins" TO "service_role";
GRANT UPDATE ON public."daily_checkins" TO "service_role";
GRANT DELETE ON public."daily_checkins" TO "service_role";
GRANT TRUNCATE ON public."daily_checkins" TO "service_role";
GRANT REFERENCES ON public."daily_checkins" TO "service_role";
GRANT TRIGGER ON public."daily_checkins" TO "service_role";
GRANT INSERT ON public."journals" TO "anon";
GRANT SELECT ON public."journals" TO "anon";
GRANT UPDATE ON public."journals" TO "anon";
GRANT DELETE ON public."journals" TO "anon";
GRANT TRUNCATE ON public."journals" TO "anon";
GRANT REFERENCES ON public."journals" TO "anon";
GRANT TRIGGER ON public."journals" TO "anon";
GRANT INSERT ON public."journals" TO "authenticated";
GRANT SELECT ON public."journals" TO "authenticated";
GRANT UPDATE ON public."journals" TO "authenticated";
GRANT DELETE ON public."journals" TO "authenticated";
GRANT TRUNCATE ON public."journals" TO "authenticated";
GRANT REFERENCES ON public."journals" TO "authenticated";
GRANT TRIGGER ON public."journals" TO "authenticated";
GRANT INSERT ON public."journals" TO "service_role";
GRANT SELECT ON public."journals" TO "service_role";
GRANT UPDATE ON public."journals" TO "service_role";
GRANT DELETE ON public."journals" TO "service_role";
GRANT TRUNCATE ON public."journals" TO "service_role";
GRANT REFERENCES ON public."journals" TO "service_role";
GRANT TRIGGER ON public."journals" TO "service_role";
GRANT INSERT ON public."daily_journals" TO "anon";
GRANT SELECT ON public."daily_journals" TO "anon";
GRANT UPDATE ON public."daily_journals" TO "anon";
GRANT DELETE ON public."daily_journals" TO "anon";
GRANT TRUNCATE ON public."daily_journals" TO "anon";
GRANT REFERENCES ON public."daily_journals" TO "anon";
GRANT TRIGGER ON public."daily_journals" TO "anon";
GRANT INSERT ON public."daily_journals" TO "authenticated";
GRANT SELECT ON public."daily_journals" TO "authenticated";
GRANT UPDATE ON public."daily_journals" TO "authenticated";
GRANT DELETE ON public."daily_journals" TO "authenticated";
GRANT TRUNCATE ON public."daily_journals" TO "authenticated";
GRANT REFERENCES ON public."daily_journals" TO "authenticated";
GRANT TRIGGER ON public."daily_journals" TO "authenticated";
GRANT INSERT ON public."daily_journals" TO "service_role";
GRANT SELECT ON public."daily_journals" TO "service_role";
GRANT UPDATE ON public."daily_journals" TO "service_role";
GRANT DELETE ON public."daily_journals" TO "service_role";
GRANT TRUNCATE ON public."daily_journals" TO "service_role";
GRANT REFERENCES ON public."daily_journals" TO "service_role";
GRANT TRIGGER ON public."daily_journals" TO "service_role";
GRANT INSERT ON public."yearly_journals" TO "anon";
GRANT SELECT ON public."yearly_journals" TO "anon";
GRANT UPDATE ON public."yearly_journals" TO "anon";
GRANT DELETE ON public."yearly_journals" TO "anon";
GRANT TRUNCATE ON public."yearly_journals" TO "anon";
GRANT REFERENCES ON public."yearly_journals" TO "anon";
GRANT TRIGGER ON public."yearly_journals" TO "anon";
GRANT INSERT ON public."yearly_journals" TO "authenticated";
GRANT SELECT ON public."yearly_journals" TO "authenticated";
GRANT UPDATE ON public."yearly_journals" TO "authenticated";
GRANT DELETE ON public."yearly_journals" TO "authenticated";
GRANT TRUNCATE ON public."yearly_journals" TO "authenticated";
GRANT REFERENCES ON public."yearly_journals" TO "authenticated";
GRANT TRIGGER ON public."yearly_journals" TO "authenticated";
GRANT INSERT ON public."yearly_journals" TO "service_role";
GRANT SELECT ON public."yearly_journals" TO "service_role";
GRANT UPDATE ON public."yearly_journals" TO "service_role";
GRANT DELETE ON public."yearly_journals" TO "service_role";
GRANT TRUNCATE ON public."yearly_journals" TO "service_role";
GRANT REFERENCES ON public."yearly_journals" TO "service_role";
GRANT TRIGGER ON public."yearly_journals" TO "service_role";
GRANT INSERT ON public."yearly_goals" TO "anon";
GRANT SELECT ON public."yearly_goals" TO "anon";
GRANT UPDATE ON public."yearly_goals" TO "anon";
GRANT DELETE ON public."yearly_goals" TO "anon";
GRANT TRUNCATE ON public."yearly_goals" TO "anon";
GRANT REFERENCES ON public."yearly_goals" TO "anon";
GRANT TRIGGER ON public."yearly_goals" TO "anon";
GRANT INSERT ON public."yearly_goals" TO "authenticated";
GRANT SELECT ON public."yearly_goals" TO "authenticated";
GRANT UPDATE ON public."yearly_goals" TO "authenticated";
GRANT DELETE ON public."yearly_goals" TO "authenticated";
GRANT TRUNCATE ON public."yearly_goals" TO "authenticated";
GRANT REFERENCES ON public."yearly_goals" TO "authenticated";
GRANT TRIGGER ON public."yearly_goals" TO "authenticated";
GRANT INSERT ON public."yearly_goals" TO "service_role";
GRANT SELECT ON public."yearly_goals" TO "service_role";
GRANT UPDATE ON public."yearly_goals" TO "service_role";
GRANT DELETE ON public."yearly_goals" TO "service_role";
GRANT TRUNCATE ON public."yearly_goals" TO "service_role";
GRANT REFERENCES ON public."yearly_goals" TO "service_role";
GRANT TRIGGER ON public."yearly_goals" TO "service_role";
GRANT INSERT ON public."yearly_highlights" TO "anon";
GRANT SELECT ON public."yearly_highlights" TO "anon";
GRANT UPDATE ON public."yearly_highlights" TO "anon";
GRANT DELETE ON public."yearly_highlights" TO "anon";
GRANT TRUNCATE ON public."yearly_highlights" TO "anon";
GRANT REFERENCES ON public."yearly_highlights" TO "anon";
GRANT TRIGGER ON public."yearly_highlights" TO "anon";
GRANT INSERT ON public."yearly_highlights" TO "authenticated";
GRANT SELECT ON public."yearly_highlights" TO "authenticated";
GRANT UPDATE ON public."yearly_highlights" TO "authenticated";
GRANT DELETE ON public."yearly_highlights" TO "authenticated";
GRANT TRUNCATE ON public."yearly_highlights" TO "authenticated";
GRANT REFERENCES ON public."yearly_highlights" TO "authenticated";
GRANT TRIGGER ON public."yearly_highlights" TO "authenticated";
GRANT INSERT ON public."yearly_highlights" TO "service_role";
GRANT SELECT ON public."yearly_highlights" TO "service_role";
GRANT UPDATE ON public."yearly_highlights" TO "service_role";
GRANT DELETE ON public."yearly_highlights" TO "service_role";
GRANT TRUNCATE ON public."yearly_highlights" TO "service_role";
GRANT REFERENCES ON public."yearly_highlights" TO "service_role";
GRANT TRIGGER ON public."yearly_highlights" TO "service_role";
GRANT INSERT ON public."yearly_lessons" TO "anon";
GRANT SELECT ON public."yearly_lessons" TO "anon";
GRANT UPDATE ON public."yearly_lessons" TO "anon";
GRANT DELETE ON public."yearly_lessons" TO "anon";
GRANT TRUNCATE ON public."yearly_lessons" TO "anon";
GRANT REFERENCES ON public."yearly_lessons" TO "anon";
GRANT TRIGGER ON public."yearly_lessons" TO "anon";
GRANT INSERT ON public."yearly_lessons" TO "authenticated";
GRANT SELECT ON public."yearly_lessons" TO "authenticated";
GRANT UPDATE ON public."yearly_lessons" TO "authenticated";
GRANT DELETE ON public."yearly_lessons" TO "authenticated";
GRANT TRUNCATE ON public."yearly_lessons" TO "authenticated";
GRANT REFERENCES ON public."yearly_lessons" TO "authenticated";
GRANT TRIGGER ON public."yearly_lessons" TO "authenticated";
GRANT INSERT ON public."yearly_lessons" TO "service_role";
GRANT SELECT ON public."yearly_lessons" TO "service_role";
GRANT UPDATE ON public."yearly_lessons" TO "service_role";
GRANT DELETE ON public."yearly_lessons" TO "service_role";
GRANT TRUNCATE ON public."yearly_lessons" TO "service_role";
GRANT REFERENCES ON public."yearly_lessons" TO "service_role";
GRANT TRIGGER ON public."yearly_lessons" TO "service_role";
GRANT INSERT ON public."future_letters" TO "anon";
GRANT SELECT ON public."future_letters" TO "anon";
GRANT UPDATE ON public."future_letters" TO "anon";
GRANT DELETE ON public."future_letters" TO "anon";
GRANT TRUNCATE ON public."future_letters" TO "anon";
GRANT REFERENCES ON public."future_letters" TO "anon";
GRANT TRIGGER ON public."future_letters" TO "anon";
GRANT INSERT ON public."future_letters" TO "authenticated";
GRANT SELECT ON public."future_letters" TO "authenticated";
GRANT UPDATE ON public."future_letters" TO "authenticated";
GRANT DELETE ON public."future_letters" TO "authenticated";
GRANT TRUNCATE ON public."future_letters" TO "authenticated";
GRANT REFERENCES ON public."future_letters" TO "authenticated";
GRANT TRIGGER ON public."future_letters" TO "authenticated";
GRANT INSERT ON public."future_letters" TO "service_role";
GRANT SELECT ON public."future_letters" TO "service_role";
GRANT UPDATE ON public."future_letters" TO "service_role";
GRANT DELETE ON public."future_letters" TO "service_role";
GRANT TRUNCATE ON public."future_letters" TO "service_role";
GRANT REFERENCES ON public."future_letters" TO "service_role";
GRANT TRIGGER ON public."future_letters" TO "service_role";
GRANT INSERT ON public."journal_media" TO "anon";
GRANT SELECT ON public."journal_media" TO "anon";
GRANT UPDATE ON public."journal_media" TO "anon";
GRANT DELETE ON public."journal_media" TO "anon";
GRANT TRUNCATE ON public."journal_media" TO "anon";
GRANT REFERENCES ON public."journal_media" TO "anon";
GRANT TRIGGER ON public."journal_media" TO "anon";
GRANT INSERT ON public."journal_media" TO "authenticated";
GRANT SELECT ON public."journal_media" TO "authenticated";
GRANT UPDATE ON public."journal_media" TO "authenticated";
GRANT DELETE ON public."journal_media" TO "authenticated";
GRANT TRUNCATE ON public."journal_media" TO "authenticated";
GRANT REFERENCES ON public."journal_media" TO "authenticated";
GRANT TRIGGER ON public."journal_media" TO "authenticated";
GRANT INSERT ON public."journal_media" TO "service_role";
GRANT SELECT ON public."journal_media" TO "service_role";
GRANT UPDATE ON public."journal_media" TO "service_role";
GRANT DELETE ON public."journal_media" TO "service_role";
GRANT TRUNCATE ON public."journal_media" TO "service_role";
GRANT REFERENCES ON public."journal_media" TO "service_role";
GRANT TRIGGER ON public."journal_media" TO "service_role";
GRANT INSERT ON public."journal_tags" TO "anon";
GRANT SELECT ON public."journal_tags" TO "anon";
GRANT UPDATE ON public."journal_tags" TO "anon";
GRANT DELETE ON public."journal_tags" TO "anon";
GRANT TRUNCATE ON public."journal_tags" TO "anon";
GRANT REFERENCES ON public."journal_tags" TO "anon";
GRANT TRIGGER ON public."journal_tags" TO "anon";
GRANT INSERT ON public."journal_tags" TO "authenticated";
GRANT SELECT ON public."journal_tags" TO "authenticated";
GRANT UPDATE ON public."journal_tags" TO "authenticated";
GRANT DELETE ON public."journal_tags" TO "authenticated";
GRANT TRUNCATE ON public."journal_tags" TO "authenticated";
GRANT REFERENCES ON public."journal_tags" TO "authenticated";
GRANT TRIGGER ON public."journal_tags" TO "authenticated";
GRANT INSERT ON public."journal_tags" TO "service_role";
GRANT SELECT ON public."journal_tags" TO "service_role";
GRANT UPDATE ON public."journal_tags" TO "service_role";
GRANT DELETE ON public."journal_tags" TO "service_role";
GRANT TRUNCATE ON public."journal_tags" TO "service_role";
GRANT REFERENCES ON public."journal_tags" TO "service_role";
GRANT TRIGGER ON public."journal_tags" TO "service_role";
GRANT INSERT ON public."journal_tag_assignments" TO "anon";
GRANT SELECT ON public."journal_tag_assignments" TO "anon";
GRANT UPDATE ON public."journal_tag_assignments" TO "anon";
GRANT DELETE ON public."journal_tag_assignments" TO "anon";
GRANT TRUNCATE ON public."journal_tag_assignments" TO "anon";
GRANT REFERENCES ON public."journal_tag_assignments" TO "anon";
GRANT TRIGGER ON public."journal_tag_assignments" TO "anon";
GRANT INSERT ON public."journal_tag_assignments" TO "authenticated";
GRANT SELECT ON public."journal_tag_assignments" TO "authenticated";
GRANT UPDATE ON public."journal_tag_assignments" TO "authenticated";
GRANT DELETE ON public."journal_tag_assignments" TO "authenticated";
GRANT TRUNCATE ON public."journal_tag_assignments" TO "authenticated";
GRANT REFERENCES ON public."journal_tag_assignments" TO "authenticated";
GRANT TRIGGER ON public."journal_tag_assignments" TO "authenticated";
GRANT INSERT ON public."journal_tag_assignments" TO "service_role";
GRANT SELECT ON public."journal_tag_assignments" TO "service_role";
GRANT UPDATE ON public."journal_tag_assignments" TO "service_role";
GRANT DELETE ON public."journal_tag_assignments" TO "service_role";
GRANT TRUNCATE ON public."journal_tag_assignments" TO "service_role";
GRANT REFERENCES ON public."journal_tag_assignments" TO "service_role";
GRANT TRIGGER ON public."journal_tag_assignments" TO "service_role";
GRANT INSERT ON public."user_missions" TO "anon";
GRANT SELECT ON public."user_missions" TO "anon";
GRANT UPDATE ON public."user_missions" TO "anon";
GRANT DELETE ON public."user_missions" TO "anon";
GRANT TRUNCATE ON public."user_missions" TO "anon";
GRANT REFERENCES ON public."user_missions" TO "anon";
GRANT TRIGGER ON public."user_missions" TO "anon";
GRANT INSERT ON public."user_missions" TO "authenticated";
GRANT SELECT ON public."user_missions" TO "authenticated";
GRANT UPDATE ON public."user_missions" TO "authenticated";
GRANT DELETE ON public."user_missions" TO "authenticated";
GRANT TRUNCATE ON public."user_missions" TO "authenticated";
GRANT REFERENCES ON public."user_missions" TO "authenticated";
GRANT TRIGGER ON public."user_missions" TO "authenticated";
GRANT INSERT ON public."user_missions" TO "service_role";
GRANT SELECT ON public."user_missions" TO "service_role";
GRANT UPDATE ON public."user_missions" TO "service_role";
GRANT DELETE ON public."user_missions" TO "service_role";
GRANT TRUNCATE ON public."user_missions" TO "service_role";
GRANT REFERENCES ON public."user_missions" TO "service_role";
GRANT TRIGGER ON public."user_missions" TO "service_role";
GRANT INSERT ON public."travel_progress" TO "anon";
GRANT SELECT ON public."travel_progress" TO "anon";
GRANT UPDATE ON public."travel_progress" TO "anon";
GRANT DELETE ON public."travel_progress" TO "anon";
GRANT TRUNCATE ON public."travel_progress" TO "anon";
GRANT REFERENCES ON public."travel_progress" TO "anon";
GRANT TRIGGER ON public."travel_progress" TO "anon";
GRANT INSERT ON public."travel_progress" TO "authenticated";
GRANT SELECT ON public."travel_progress" TO "authenticated";
GRANT UPDATE ON public."travel_progress" TO "authenticated";
GRANT DELETE ON public."travel_progress" TO "authenticated";
GRANT TRUNCATE ON public."travel_progress" TO "authenticated";
GRANT REFERENCES ON public."travel_progress" TO "authenticated";
GRANT TRIGGER ON public."travel_progress" TO "authenticated";
GRANT INSERT ON public."travel_progress" TO "service_role";
GRANT SELECT ON public."travel_progress" TO "service_role";
GRANT UPDATE ON public."travel_progress" TO "service_role";
GRANT DELETE ON public."travel_progress" TO "service_role";
GRANT TRUNCATE ON public."travel_progress" TO "service_role";
GRANT REFERENCES ON public."travel_progress" TO "service_role";
GRANT TRIGGER ON public."travel_progress" TO "service_role";
GRANT INSERT ON public."user_checkpoint_progress" TO "anon";
GRANT SELECT ON public."user_checkpoint_progress" TO "anon";
GRANT UPDATE ON public."user_checkpoint_progress" TO "anon";
GRANT DELETE ON public."user_checkpoint_progress" TO "anon";
GRANT TRUNCATE ON public."user_checkpoint_progress" TO "anon";
GRANT REFERENCES ON public."user_checkpoint_progress" TO "anon";
GRANT TRIGGER ON public."user_checkpoint_progress" TO "anon";
GRANT INSERT ON public."user_checkpoint_progress" TO "authenticated";
GRANT SELECT ON public."user_checkpoint_progress" TO "authenticated";
GRANT UPDATE ON public."user_checkpoint_progress" TO "authenticated";
GRANT DELETE ON public."user_checkpoint_progress" TO "authenticated";
GRANT TRUNCATE ON public."user_checkpoint_progress" TO "authenticated";
GRANT REFERENCES ON public."user_checkpoint_progress" TO "authenticated";
GRANT TRIGGER ON public."user_checkpoint_progress" TO "authenticated";
GRANT INSERT ON public."user_checkpoint_progress" TO "service_role";
GRANT SELECT ON public."user_checkpoint_progress" TO "service_role";
GRANT UPDATE ON public."user_checkpoint_progress" TO "service_role";
GRANT DELETE ON public."user_checkpoint_progress" TO "service_role";
GRANT TRUNCATE ON public."user_checkpoint_progress" TO "service_role";
GRANT REFERENCES ON public."user_checkpoint_progress" TO "service_role";
GRANT TRIGGER ON public."user_checkpoint_progress" TO "service_role";
GRANT INSERT ON public."travel_events" TO "anon";
GRANT SELECT ON public."travel_events" TO "anon";
GRANT UPDATE ON public."travel_events" TO "anon";
GRANT DELETE ON public."travel_events" TO "anon";
GRANT TRUNCATE ON public."travel_events" TO "anon";
GRANT REFERENCES ON public."travel_events" TO "anon";
GRANT TRIGGER ON public."travel_events" TO "anon";
GRANT INSERT ON public."travel_events" TO "authenticated";
GRANT SELECT ON public."travel_events" TO "authenticated";
GRANT UPDATE ON public."travel_events" TO "authenticated";
GRANT DELETE ON public."travel_events" TO "authenticated";
GRANT TRUNCATE ON public."travel_events" TO "authenticated";
GRANT REFERENCES ON public."travel_events" TO "authenticated";
GRANT TRIGGER ON public."travel_events" TO "authenticated";
GRANT INSERT ON public."travel_events" TO "service_role";
GRANT SELECT ON public."travel_events" TO "service_role";
GRANT UPDATE ON public."travel_events" TO "service_role";
GRANT DELETE ON public."travel_events" TO "service_role";
GRANT TRUNCATE ON public."travel_events" TO "service_role";
GRANT REFERENCES ON public."travel_events" TO "service_role";
GRANT TRIGGER ON public."travel_events" TO "service_role";
GRANT INSERT ON public."unlocked_provinces" TO "anon";
GRANT SELECT ON public."unlocked_provinces" TO "anon";
GRANT UPDATE ON public."unlocked_provinces" TO "anon";
GRANT DELETE ON public."unlocked_provinces" TO "anon";
GRANT TRUNCATE ON public."unlocked_provinces" TO "anon";
GRANT REFERENCES ON public."unlocked_provinces" TO "anon";
GRANT TRIGGER ON public."unlocked_provinces" TO "anon";
GRANT INSERT ON public."unlocked_provinces" TO "authenticated";
GRANT SELECT ON public."unlocked_provinces" TO "authenticated";
GRANT UPDATE ON public."unlocked_provinces" TO "authenticated";
GRANT DELETE ON public."unlocked_provinces" TO "authenticated";
GRANT TRUNCATE ON public."unlocked_provinces" TO "authenticated";
GRANT REFERENCES ON public."unlocked_provinces" TO "authenticated";
GRANT TRIGGER ON public."unlocked_provinces" TO "authenticated";
GRANT INSERT ON public."unlocked_provinces" TO "service_role";
GRANT SELECT ON public."unlocked_provinces" TO "service_role";
GRANT UPDATE ON public."unlocked_provinces" TO "service_role";
GRANT DELETE ON public."unlocked_provinces" TO "service_role";
GRANT TRUNCATE ON public."unlocked_provinces" TO "service_role";
GRANT REFERENCES ON public."unlocked_provinces" TO "service_role";
GRANT TRIGGER ON public."unlocked_provinces" TO "service_role";
GRANT INSERT ON public."unlocked_landmarks" TO "anon";
GRANT SELECT ON public."unlocked_landmarks" TO "anon";
GRANT UPDATE ON public."unlocked_landmarks" TO "anon";
GRANT DELETE ON public."unlocked_landmarks" TO "anon";
GRANT TRUNCATE ON public."unlocked_landmarks" TO "anon";
GRANT REFERENCES ON public."unlocked_landmarks" TO "anon";
GRANT TRIGGER ON public."unlocked_landmarks" TO "anon";
GRANT INSERT ON public."unlocked_landmarks" TO "authenticated";
GRANT SELECT ON public."unlocked_landmarks" TO "authenticated";
GRANT UPDATE ON public."unlocked_landmarks" TO "authenticated";
GRANT DELETE ON public."unlocked_landmarks" TO "authenticated";
GRANT TRUNCATE ON public."unlocked_landmarks" TO "authenticated";
GRANT REFERENCES ON public."unlocked_landmarks" TO "authenticated";
GRANT TRIGGER ON public."unlocked_landmarks" TO "authenticated";
GRANT INSERT ON public."unlocked_landmarks" TO "service_role";
GRANT SELECT ON public."unlocked_landmarks" TO "service_role";
GRANT UPDATE ON public."unlocked_landmarks" TO "service_role";
GRANT DELETE ON public."unlocked_landmarks" TO "service_role";
GRANT TRUNCATE ON public."unlocked_landmarks" TO "service_role";
GRANT REFERENCES ON public."unlocked_landmarks" TO "service_role";
GRANT TRIGGER ON public."unlocked_landmarks" TO "service_role";
GRANT INSERT ON public."unlocked_foods" TO "anon";
GRANT SELECT ON public."unlocked_foods" TO "anon";
GRANT UPDATE ON public."unlocked_foods" TO "anon";
GRANT DELETE ON public."unlocked_foods" TO "anon";
GRANT TRUNCATE ON public."unlocked_foods" TO "anon";
GRANT REFERENCES ON public."unlocked_foods" TO "anon";
GRANT TRIGGER ON public."unlocked_foods" TO "anon";
GRANT INSERT ON public."unlocked_foods" TO "authenticated";
GRANT SELECT ON public."unlocked_foods" TO "authenticated";
GRANT UPDATE ON public."unlocked_foods" TO "authenticated";
GRANT DELETE ON public."unlocked_foods" TO "authenticated";
GRANT TRUNCATE ON public."unlocked_foods" TO "authenticated";
GRANT REFERENCES ON public."unlocked_foods" TO "authenticated";
GRANT TRIGGER ON public."unlocked_foods" TO "authenticated";
GRANT INSERT ON public."unlocked_foods" TO "service_role";
GRANT SELECT ON public."unlocked_foods" TO "service_role";
GRANT UPDATE ON public."unlocked_foods" TO "service_role";
GRANT DELETE ON public."unlocked_foods" TO "service_role";
GRANT TRUNCATE ON public."unlocked_foods" TO "service_role";
GRANT REFERENCES ON public."unlocked_foods" TO "service_role";
GRANT TRIGGER ON public."unlocked_foods" TO "service_role";
GRANT INSERT ON public."unlocked_province_items" TO "anon";
GRANT SELECT ON public."unlocked_province_items" TO "anon";
GRANT UPDATE ON public."unlocked_province_items" TO "anon";
GRANT DELETE ON public."unlocked_province_items" TO "anon";
GRANT TRUNCATE ON public."unlocked_province_items" TO "anon";
GRANT REFERENCES ON public."unlocked_province_items" TO "anon";
GRANT TRIGGER ON public."unlocked_province_items" TO "anon";
GRANT INSERT ON public."unlocked_province_items" TO "authenticated";
GRANT SELECT ON public."unlocked_province_items" TO "authenticated";
GRANT UPDATE ON public."unlocked_province_items" TO "authenticated";
GRANT DELETE ON public."unlocked_province_items" TO "authenticated";
GRANT TRUNCATE ON public."unlocked_province_items" TO "authenticated";
GRANT REFERENCES ON public."unlocked_province_items" TO "authenticated";
GRANT TRIGGER ON public."unlocked_province_items" TO "authenticated";
GRANT INSERT ON public."unlocked_province_items" TO "service_role";
GRANT SELECT ON public."unlocked_province_items" TO "service_role";
GRANT UPDATE ON public."unlocked_province_items" TO "service_role";
GRANT DELETE ON public."unlocked_province_items" TO "service_role";
GRANT TRUNCATE ON public."unlocked_province_items" TO "service_role";
GRANT REFERENCES ON public."unlocked_province_items" TO "service_role";
GRANT TRIGGER ON public."unlocked_province_items" TO "service_role";
GRANT INSERT ON public."energy_transactions" TO "anon";
GRANT SELECT ON public."energy_transactions" TO "anon";
GRANT UPDATE ON public."energy_transactions" TO "anon";
GRANT DELETE ON public."energy_transactions" TO "anon";
GRANT TRUNCATE ON public."energy_transactions" TO "anon";
GRANT REFERENCES ON public."energy_transactions" TO "anon";
GRANT TRIGGER ON public."energy_transactions" TO "anon";
GRANT INSERT ON public."energy_transactions" TO "authenticated";
GRANT SELECT ON public."energy_transactions" TO "authenticated";
GRANT UPDATE ON public."energy_transactions" TO "authenticated";
GRANT DELETE ON public."energy_transactions" TO "authenticated";
GRANT TRUNCATE ON public."energy_transactions" TO "authenticated";
GRANT REFERENCES ON public."energy_transactions" TO "authenticated";
GRANT TRIGGER ON public."energy_transactions" TO "authenticated";
GRANT INSERT ON public."energy_transactions" TO "service_role";
GRANT SELECT ON public."energy_transactions" TO "service_role";
GRANT UPDATE ON public."energy_transactions" TO "service_role";
GRANT DELETE ON public."energy_transactions" TO "service_role";
GRANT TRUNCATE ON public."energy_transactions" TO "service_role";
GRANT REFERENCES ON public."energy_transactions" TO "service_role";
GRANT TRIGGER ON public."energy_transactions" TO "service_role";
GRANT INSERT ON public."mission_templates" TO "anon";
GRANT SELECT ON public."mission_templates" TO "anon";
GRANT UPDATE ON public."mission_templates" TO "anon";
GRANT DELETE ON public."mission_templates" TO "anon";
GRANT TRUNCATE ON public."mission_templates" TO "anon";
GRANT REFERENCES ON public."mission_templates" TO "anon";
GRANT TRIGGER ON public."mission_templates" TO "anon";
GRANT INSERT ON public."mission_templates" TO "authenticated";
GRANT SELECT ON public."mission_templates" TO "authenticated";
GRANT UPDATE ON public."mission_templates" TO "authenticated";
GRANT DELETE ON public."mission_templates" TO "authenticated";
GRANT TRUNCATE ON public."mission_templates" TO "authenticated";
GRANT REFERENCES ON public."mission_templates" TO "authenticated";
GRANT TRIGGER ON public."mission_templates" TO "authenticated";
GRANT INSERT ON public."mission_templates" TO "service_role";
GRANT SELECT ON public."mission_templates" TO "service_role";
GRANT UPDATE ON public."mission_templates" TO "service_role";
GRANT DELETE ON public."mission_templates" TO "service_role";
GRANT TRUNCATE ON public."mission_templates" TO "service_role";
GRANT REFERENCES ON public."mission_templates" TO "service_role";
GRANT TRIGGER ON public."mission_templates" TO "service_role";
GRANT INSERT ON public."provinces" TO "anon";
GRANT SELECT ON public."provinces" TO "anon";
GRANT UPDATE ON public."provinces" TO "anon";
GRANT DELETE ON public."provinces" TO "anon";
GRANT TRUNCATE ON public."provinces" TO "anon";
GRANT REFERENCES ON public."provinces" TO "anon";
GRANT TRIGGER ON public."provinces" TO "anon";
GRANT INSERT ON public."provinces" TO "authenticated";
GRANT SELECT ON public."provinces" TO "authenticated";
GRANT UPDATE ON public."provinces" TO "authenticated";
GRANT DELETE ON public."provinces" TO "authenticated";
GRANT TRUNCATE ON public."provinces" TO "authenticated";
GRANT REFERENCES ON public."provinces" TO "authenticated";
GRANT TRIGGER ON public."provinces" TO "authenticated";
GRANT INSERT ON public."provinces" TO "service_role";
GRANT SELECT ON public."provinces" TO "service_role";
GRANT UPDATE ON public."provinces" TO "service_role";
GRANT DELETE ON public."provinces" TO "service_role";
GRANT TRUNCATE ON public."provinces" TO "service_role";
GRANT REFERENCES ON public."provinces" TO "service_role";
GRANT TRIGGER ON public."provinces" TO "service_role";
GRANT INSERT ON public."landmarks" TO "anon";
GRANT SELECT ON public."landmarks" TO "anon";
GRANT UPDATE ON public."landmarks" TO "anon";
GRANT DELETE ON public."landmarks" TO "anon";
GRANT TRUNCATE ON public."landmarks" TO "anon";
GRANT REFERENCES ON public."landmarks" TO "anon";
GRANT TRIGGER ON public."landmarks" TO "anon";
GRANT INSERT ON public."landmarks" TO "authenticated";
GRANT SELECT ON public."landmarks" TO "authenticated";
GRANT UPDATE ON public."landmarks" TO "authenticated";
GRANT DELETE ON public."landmarks" TO "authenticated";
GRANT TRUNCATE ON public."landmarks" TO "authenticated";
GRANT REFERENCES ON public."landmarks" TO "authenticated";
GRANT TRIGGER ON public."landmarks" TO "authenticated";
GRANT INSERT ON public."landmarks" TO "service_role";
GRANT SELECT ON public."landmarks" TO "service_role";
GRANT UPDATE ON public."landmarks" TO "service_role";
GRANT DELETE ON public."landmarks" TO "service_role";
GRANT TRUNCATE ON public."landmarks" TO "service_role";
GRANT REFERENCES ON public."landmarks" TO "service_role";
GRANT TRIGGER ON public."landmarks" TO "service_role";
GRANT INSERT ON public."foods" TO "anon";
GRANT SELECT ON public."foods" TO "anon";
GRANT UPDATE ON public."foods" TO "anon";
GRANT DELETE ON public."foods" TO "anon";
GRANT TRUNCATE ON public."foods" TO "anon";
GRANT REFERENCES ON public."foods" TO "anon";
GRANT TRIGGER ON public."foods" TO "anon";
GRANT INSERT ON public."foods" TO "authenticated";
GRANT SELECT ON public."foods" TO "authenticated";
GRANT UPDATE ON public."foods" TO "authenticated";
GRANT DELETE ON public."foods" TO "authenticated";
GRANT TRUNCATE ON public."foods" TO "authenticated";
GRANT REFERENCES ON public."foods" TO "authenticated";
GRANT TRIGGER ON public."foods" TO "authenticated";
GRANT INSERT ON public."foods" TO "service_role";
GRANT SELECT ON public."foods" TO "service_role";
GRANT UPDATE ON public."foods" TO "service_role";
GRANT DELETE ON public."foods" TO "service_role";
GRANT TRUNCATE ON public."foods" TO "service_role";
GRANT REFERENCES ON public."foods" TO "service_role";
GRANT TRIGGER ON public."foods" TO "service_role";
GRANT INSERT ON public."province_items" TO "anon";
GRANT SELECT ON public."province_items" TO "anon";
GRANT UPDATE ON public."province_items" TO "anon";
GRANT DELETE ON public."province_items" TO "anon";
GRANT TRUNCATE ON public."province_items" TO "anon";
GRANT REFERENCES ON public."province_items" TO "anon";
GRANT TRIGGER ON public."province_items" TO "anon";
GRANT INSERT ON public."province_items" TO "authenticated";
GRANT SELECT ON public."province_items" TO "authenticated";
GRANT UPDATE ON public."province_items" TO "authenticated";
GRANT DELETE ON public."province_items" TO "authenticated";
GRANT TRUNCATE ON public."province_items" TO "authenticated";
GRANT REFERENCES ON public."province_items" TO "authenticated";
GRANT TRIGGER ON public."province_items" TO "authenticated";
GRANT INSERT ON public."province_items" TO "service_role";
GRANT SELECT ON public."province_items" TO "service_role";
GRANT UPDATE ON public."province_items" TO "service_role";
GRANT DELETE ON public."province_items" TO "service_role";
GRANT TRUNCATE ON public."province_items" TO "service_role";
GRANT REFERENCES ON public."province_items" TO "service_role";
GRANT TRIGGER ON public."province_items" TO "service_role";
GRANT INSERT ON public."province_checkpoints" TO "anon";
GRANT SELECT ON public."province_checkpoints" TO "anon";
GRANT UPDATE ON public."province_checkpoints" TO "anon";
GRANT DELETE ON public."province_checkpoints" TO "anon";
GRANT TRUNCATE ON public."province_checkpoints" TO "anon";
GRANT REFERENCES ON public."province_checkpoints" TO "anon";
GRANT TRIGGER ON public."province_checkpoints" TO "anon";
GRANT INSERT ON public."province_checkpoints" TO "authenticated";
GRANT SELECT ON public."province_checkpoints" TO "authenticated";
GRANT UPDATE ON public."province_checkpoints" TO "authenticated";
GRANT DELETE ON public."province_checkpoints" TO "authenticated";
GRANT TRUNCATE ON public."province_checkpoints" TO "authenticated";
GRANT REFERENCES ON public."province_checkpoints" TO "authenticated";
GRANT TRIGGER ON public."province_checkpoints" TO "authenticated";
GRANT INSERT ON public."province_checkpoints" TO "service_role";
GRANT SELECT ON public."province_checkpoints" TO "service_role";
GRANT UPDATE ON public."province_checkpoints" TO "service_role";
GRANT DELETE ON public."province_checkpoints" TO "service_role";
GRANT TRUNCATE ON public."province_checkpoints" TO "service_role";
GRANT REFERENCES ON public."province_checkpoints" TO "service_role";
GRANT TRIGGER ON public."province_checkpoints" TO "service_role";
GRANT INSERT ON public."checkpoint_rewards" TO "anon";
GRANT SELECT ON public."checkpoint_rewards" TO "anon";
GRANT UPDATE ON public."checkpoint_rewards" TO "anon";
GRANT DELETE ON public."checkpoint_rewards" TO "anon";
GRANT TRUNCATE ON public."checkpoint_rewards" TO "anon";
GRANT REFERENCES ON public."checkpoint_rewards" TO "anon";
GRANT TRIGGER ON public."checkpoint_rewards" TO "anon";
GRANT INSERT ON public."checkpoint_rewards" TO "authenticated";
GRANT SELECT ON public."checkpoint_rewards" TO "authenticated";
GRANT UPDATE ON public."checkpoint_rewards" TO "authenticated";
GRANT DELETE ON public."checkpoint_rewards" TO "authenticated";
GRANT TRUNCATE ON public."checkpoint_rewards" TO "authenticated";
GRANT REFERENCES ON public."checkpoint_rewards" TO "authenticated";
GRANT TRIGGER ON public."checkpoint_rewards" TO "authenticated";
GRANT INSERT ON public."checkpoint_rewards" TO "service_role";
GRANT SELECT ON public."checkpoint_rewards" TO "service_role";
GRANT UPDATE ON public."checkpoint_rewards" TO "service_role";
GRANT DELETE ON public."checkpoint_rewards" TO "service_role";
GRANT TRUNCATE ON public."checkpoint_rewards" TO "service_role";
GRANT REFERENCES ON public."checkpoint_rewards" TO "service_role";
GRANT TRIGGER ON public."checkpoint_rewards" TO "service_role";

$bootstrap$;
END IF;
END $baseline$;

